name: Deploy MkDocs (baseline)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs + Material + Print plugin
        run: |
          pip install mkdocs-material mkdocs-print-site-plugin

      - name: Build HTML site
        run: mkdocs build   # (no --strict to avoid failing on warnings)

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - uses: actions/deploy-pages@v4
